name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::767828728771:role/GitHubActionsEKSRole
          aws-region: ap-south-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t my-eks-web-app:${{ github.sha }} .

      - name: Tag image
        run: |
          docker tag my-eks-web-app:${{ github.sha }} \
          767828728771.dkr.ecr.ap-south-1.amazonaws.com/my-eks-web-app:${{ github.sha }}

      - name: Push image
        run: |
          docker push \
          767828728771.dkr.ecr.ap-south-1.amazonaws.com/my-eks-web-app:${{ github.sha }}
